//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationRoles = new HashSet<ApplicationRole>();
            this.Permissions = new HashSet<Permission>();
            this.UnitAssociations = new HashSet<UnitAssociation>();
        }
    
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string Abbr { get; set; }
        public string Location { get; set; }
        public string IconLocation { get; set; }
        public bool Inactive { get; set; }
        public string WebServiceHash { get; set; }
        public string Salt { get; set; }
    
        public virtual ICollection<ApplicationRole> ApplicationRoles { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<UnitAssociation> UnitAssociations { get; set; }
    }
}
