//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserUnits_V
    {
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmployeeID { get; set; }
        public int UnitID { get; set; }
        public string FullName { get; set; }
        public string PPS_Code { get; set; }
        public string FIS_Code { get; set; }
        public bool Inactive { get; set; }
    }
}
