//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    
    public partial class BudgetAdjustmentUploadDataResults
    {
        public string UNIV_FISCAL_YEAR { get; set; }
        public string FIN_COA_CD { get; set; }
        public string ACCOUNT_NBR { get; set; }
        public string SUB_ACCT_NBR { get; set; }
        public string FIN_OBJECT_CD { get; set; }
        public string FIN_SUB_OBJ_CD { get; set; }
        public string FIN_BALANCE_TYP_CD { get; set; }
        public string FIN_OBJ_TYP_CD { get; set; }
        public string UNIV_FISCAL_PRD_CD { get; set; }
        public string FDOC_TYP_CD { get; set; }
        public string FS_ORIGIN_CD { get; set; }
        public string FDOC_NBR { get; set; }
        public string TRN_ENTR_SEQ_NBR { get; set; }
        public string TRN_LDGR_ENTR_DESC { get; set; }
        public string TRN_LDGR_ENTR_AMT { get; set; }
        public string TRN_DEBIT_CRDT_CD { get; set; }
        public string TRANSACTION_DT { get; set; }
        public string ORG_DOC_NBR { get; set; }
        public string PROJECT_CD { get; set; }
        public string ORG_REFERENCE_ID { get; set; }
        public string FDOC_REF_TYP_CD { get; set; }
        public string FS_REF_ORIGIN_CD { get; set; }
        public string FDOC_REF_NBR { get; set; }
        public string FDOC_REVERSAL_DT { get; set; }
        public string TRN_ENCUM_UPDT_CD { get; set; }
    }
}
