//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CATBERT3Entities1 : DbContext
    {
        public CATBERT3Entities1()
            : base("name=CATBERT3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<UnitAssociation> UnitAssociations { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ApplicationRoles_V> ApplicationRoles_V { get; set; }
        public DbSet<ApplicationUsers_V> ApplicationUsers_V { get; set; }
        public DbSet<ApplicationUserUnits_V> ApplicationUserUnits_V { get; set; }
    
        [EdmFunction("CATBERT3Entities1", "udf_Catbert3_vUserRoles")]
        public virtual IQueryable<udf_Catbert3_vUserRoles_Result> udf_Catbert3_vUserRoles(string applicationsAbbr)
        {
            var applicationsAbbrParameter = applicationsAbbr != null ?
                new ObjectParameter("applicationsAbbr", applicationsAbbr) :
                new ObjectParameter("applicationsAbbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_Catbert3_vUserRoles_Result>("[CATBERT3Entities1].[udf_Catbert3_vUserRoles](@applicationsAbbr)", applicationsAbbrParameter);
        }
    
        [EdmFunction("CATBERT3Entities1", "udf_Catbert3_vUsers")]
        public virtual IQueryable<udf_Catbert3_vUsers_Result> udf_Catbert3_vUsers(string applicationsAbbr)
        {
            var applicationsAbbrParameter = applicationsAbbr != null ?
                new ObjectParameter("applicationsAbbr", applicationsAbbr) :
                new ObjectParameter("applicationsAbbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_Catbert3_vUsers_Result>("[CATBERT3Entities1].[udf_Catbert3_vUsers](@applicationsAbbr)", applicationsAbbrParameter);
        }
    
        [EdmFunction("CATBERT3Entities1", "udf_Catbert3_vUserUnits")]
        public virtual IQueryable<udf_Catbert3_vUserUnits_Result> udf_Catbert3_vUserUnits(string applicationsAbbr)
        {
            var applicationsAbbrParameter = applicationsAbbr != null ?
                new ObjectParameter("applicationsAbbr", applicationsAbbr) :
                new ObjectParameter("applicationsAbbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_Catbert3_vUserUnits_Result>("[CATBERT3Entities1].[udf_Catbert3_vUserUnits](@applicationsAbbr)", applicationsAbbrParameter);
        }
    }
}
