//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CATBERT3Entities : DbContext
    {
        public CATBERT3Entities()
            : base("name=CATBERT3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<UnitAssociation> UnitAssociations { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ApplicationRoles_V> ApplicationRoles_V { get; set; }
        public DbSet<ApplicationUsers_V> ApplicationUsers_V { get; set; }
    }
}
