//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralAccount
    {
        public string PK_CentralAccounts { get; set; }
        public string OrgId { get; set; }
        public string SchoolCode { get; set; }
        public string Chart { get; set; }
        public string Account { get; set; }
        public string SubAccount { get; set; }
        public string ObjectConsolidation { get; set; }
        public string FundingObjectConsolidation { get; set; }
        public string SubObject { get; set; }
        public string FunctionCode { get; set; }
        public string TransDocOriginCode { get; set; }
        public string OpFund { get; set; }
        public bool IsActive { get; set; }
    }
}
