//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets5572C5C49A369A110AC035B54E6150596A8A3D1106843F0A7508026AF79B1579))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets5572C5C49A369A110AC035B54E6150596A8A3D1106843F0A7508026AF79B1579 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets5572C5C49A369A110AC035B54E6150596A8A3D1106843F0A7508026AF79B1579()
        {
            this.EdmEntityContainerName = "FISDataMartEntities";
            this.StoreEntityContainerName = "FISDataMartModelStoreContainer";
            this.HashOverMappingClosure = "b07bfdd1f0732dadb6c09cc19d6fc82843b9d698c2ab22066c341721bab8988f";
            this.HashOverAllExtentViews = "66744679e5e4659507dc7780960565895448d505668995bf11e4802b7080cbb3";
            this.ViewCount = 10;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for FISDataMartModelStoreContainer.Catbert3_vLogin
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartModelStoreContainer.Catbert3_vLogin", @"
    SELECT VALUE -- Constructing Catbert3_vLogin
        [FISDataMartModel.Store.Catbert3_vLogin](T1.[Catbert3_vLogin.LoginID], T1.[Catbert3_vLogin.UserID])
    FROM (
        SELECT 
            T.LoginID AS [Catbert3_vLogin.LoginID], 
            T.UserID AS [Catbert3_vLogin.UserID], 
            True AS _from0
        FROM FISDataMartEntities.Catbert3_vLogin AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartEntities.Catbert3_vLogin
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartEntities.Catbert3_vLogin", @"
    SELECT VALUE -- Constructing Catbert3_vLogin
        [FISDataMartModel.Catbert3_vLogin](T1.[Catbert3_vLogin.LoginID], T1.[Catbert3_vLogin.UserID])
    FROM (
        SELECT 
            T.LoginID AS [Catbert3_vLogin.LoginID], 
            T.UserID AS [Catbert3_vLogin.UserID], 
            True AS _from0
        FROM FISDataMartModelStoreContainer.Catbert3_vLogin AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartModelStoreContainer.Catbert3_vSchools
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartModelStoreContainer.Catbert3_vSchools", @"
    SELECT VALUE -- Constructing Catbert3_vSchools
        [FISDataMartModel.Store.Catbert3_vSchools](T1.[Catbert3_vSchools.SchoolCode], T1.[Catbert3_vSchools.ShortDescription], T1.[Catbert3_vSchools.LongDescription], T1.[Catbert3_vSchools.Abbreviation])
    FROM (
        SELECT 
            T.SchoolCode AS [Catbert3_vSchools.SchoolCode], 
            T.ShortDescription AS [Catbert3_vSchools.ShortDescription], 
            T.LongDescription AS [Catbert3_vSchools.LongDescription], 
            T.Abbreviation AS [Catbert3_vSchools.Abbreviation], 
            True AS _from0
        FROM FISDataMartEntities.Catbert3_vSchools AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartEntities.Catbert3_vSchools
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartEntities.Catbert3_vSchools", @"
    SELECT VALUE -- Constructing Catbert3_vSchools
        [FISDataMartModel.Catbert3_vSchools](T1.[Catbert3_vSchools.SchoolCode], T1.[Catbert3_vSchools.ShortDescription], T1.[Catbert3_vSchools.LongDescription], T1.[Catbert3_vSchools.Abbreviation])
    FROM (
        SELECT 
            T.SchoolCode AS [Catbert3_vSchools.SchoolCode], 
            T.ShortDescription AS [Catbert3_vSchools.ShortDescription], 
            T.LongDescription AS [Catbert3_vSchools.LongDescription], 
            T.Abbreviation AS [Catbert3_vSchools.Abbreviation], 
            True AS _from0
        FROM FISDataMartModelStoreContainer.Catbert3_vSchools AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartModelStoreContainer.PPSDataMart_vSchools
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartModelStoreContainer.PPSDataMart_vSchools", @"
    SELECT VALUE -- Constructing PPSDataMart_vSchools
        [FISDataMartModel.Store.PPSDataMart_vSchools](T1.[PPSDataMart_vSchools.SchoolCode], T1.[PPSDataMart_vSchools.ShortDescription], T1.[PPSDataMart_vSchools.LongDescription], T1.[PPSDataMart_vSchools.Abbreviation])
    FROM (
        SELECT 
            T.SchoolCode AS [PPSDataMart_vSchools.SchoolCode], 
            T.ShortDescription AS [PPSDataMart_vSchools.ShortDescription], 
            T.LongDescription AS [PPSDataMart_vSchools.LongDescription], 
            T.Abbreviation AS [PPSDataMart_vSchools.Abbreviation], 
            True AS _from0
        FROM FISDataMartEntities.PPSDataMart_vSchools AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartEntities.PPSDataMart_vSchools
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartEntities.PPSDataMart_vSchools", @"
    SELECT VALUE -- Constructing PPSDataMart_vSchools
        [FISDataMartModel.PPSDataMart_vSchools](T1.[PPSDataMart_vSchools.SchoolCode], T1.[PPSDataMart_vSchools.ShortDescription], T1.[PPSDataMart_vSchools.LongDescription], T1.[PPSDataMart_vSchools.Abbreviation])
    FROM (
        SELECT 
            T.SchoolCode AS [PPSDataMart_vSchools.SchoolCode], 
            T.ShortDescription AS [PPSDataMart_vSchools.ShortDescription], 
            T.LongDescription AS [PPSDataMart_vSchools.LongDescription], 
            T.Abbreviation AS [PPSDataMart_vSchools.Abbreviation], 
            True AS _from0
        FROM FISDataMartModelStoreContainer.PPSDataMart_vSchools AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartModelStoreContainer.UnitFiles
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartModelStoreContainer.UnitFiles", @"
    SELECT VALUE -- Constructing UnitFiles
        [FISDataMartModel.Store.UnitFiles](T1.UnitFiles_Id, T1.UnitFiles_UnitId, T1.UnitFiles_Filename, T1.UnitFiles_SchoolCode, T1.UnitFiles_Created, T1.UnitFiles_CreatedBy, T1.UnitFiles_Uploaded, T1.UnitFiles_UploadedBy)
    FROM (
        SELECT 
            T.Id AS UnitFiles_Id, 
            T.UnitId AS UnitFiles_UnitId, 
            T.Filename AS UnitFiles_Filename, 
            T.SchoolCode AS UnitFiles_SchoolCode, 
            T.Created AS UnitFiles_Created, 
            T.CreatedBy AS UnitFiles_CreatedBy, 
            T.Uploaded AS UnitFiles_Uploaded, 
            T.UploadedBy AS UnitFiles_UploadedBy, 
            True AS _from0
        FROM FISDataMartEntities.UnitFiles AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartEntities.UnitFiles
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartEntities.UnitFiles", @"
    SELECT VALUE -- Constructing UnitFiles
        [FISDataMartModel.UnitFile](T1.UnitFile_UnitId, T1.UnitFile_Filename, T1.UnitFile_SchoolCode, T1.UnitFile_Id, T1.UnitFile_Created, T1.UnitFile_CreatedBy, T1.UnitFile_Uploaded, T1.UnitFile_UploadedBy)
    FROM (
        SELECT 
            T.UnitId AS UnitFile_UnitId, 
            T.Filename AS UnitFile_Filename, 
            T.SchoolCode AS UnitFile_SchoolCode, 
            T.Id AS UnitFile_Id, 
            T.Created AS UnitFile_Created, 
            T.CreatedBy AS UnitFile_CreatedBy, 
            T.Uploaded AS UnitFile_Uploaded, 
            T.UploadedBy AS UnitFile_UploadedBy, 
            True AS _from0
        FROM FISDataMartModelStoreContainer.UnitFiles AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartModelStoreContainer.ExpiredAccountsV
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartModelStoreContainer.ExpiredAccountsV", @"
    SELECT VALUE -- Constructing ExpiredAccountsV
        [FISDataMartModel.Store.ExpiredAccountsV](T1.ExpiredAccountsV_AccountNum, T1.ExpiredAccountsV_ExpirationDate, T1.ExpiredAccountsV_Amount, T1.[ExpiredAccountsV.Level3_OrgCode], T1.ExpiredAccountsV_MgrId, T1.ExpiredAccountsV_MgrName)
    FROM (
        SELECT 
            T.AccountNum AS ExpiredAccountsV_AccountNum, 
            T.ExpirationDate AS ExpiredAccountsV_ExpirationDate, 
            CAST(NULL AS [Edm.Decimal]) AS ExpiredAccountsV_Amount, 
            T.Level3_OrgCode AS [ExpiredAccountsV.Level3_OrgCode], 
            T.MgrId AS ExpiredAccountsV_MgrId, 
            T.MgrName AS ExpiredAccountsV_MgrName, 
            True AS _from0
        FROM FISDataMartEntities.ExpiredAccounts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartEntities.ExpiredAccounts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartEntities.ExpiredAccounts", @"
    SELECT VALUE -- Constructing ExpiredAccounts
        [FISDataMartModel.ExpiredAccount](T1.ExpiredAccount_AccountNum, T1.ExpiredAccount_ExpirationDate, T1.[ExpiredAccount.Level3_OrgCode], T1.ExpiredAccount_MgrId, T1.ExpiredAccount_MgrName)
    FROM (
        SELECT 
            T.AccountNum AS ExpiredAccount_AccountNum, 
            T.ExpirationDate AS ExpiredAccount_ExpirationDate, 
            T.Level3_OrgCode AS [ExpiredAccount.Level3_OrgCode], 
            T.MgrId AS ExpiredAccount_MgrId, 
            T.MgrName AS ExpiredAccount_MgrName, 
            True AS _from0
        FROM FISDataMartModelStoreContainer.ExpiredAccountsV AS T
    ) AS T1");
        }
    }
}
