//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets1A0785AD152F3F740055703F3F413280CF8A76271F5B529593C3BD7B5899A8A3))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets1A0785AD152F3F740055703F3F413280CF8A76271F5B529593C3BD7B5899A8A3 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets1A0785AD152F3F740055703F3F413280CF8A76271F5B529593C3BD7B5899A8A3()
        {
            this.EdmEntityContainerName = "FISDataMartEntities";
            this.StoreEntityContainerName = "FISDataMartModelStoreContainer";
            this.HashOverMappingClosure = "cc5eadabf1a9e4d00181b5d5b26fba787d4271958748c59629522571b096b545";
            this.HashOverAllExtentViews = "c8ba26730aaa1e48922a1aa248ba9684346419c4526971e7006e9aacd3e533f0";
            this.ViewCount = 8;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for FISDataMartModelStoreContainer.Catbert3_vLogin
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartModelStoreContainer.Catbert3_vLogin", @"
    SELECT VALUE -- Constructing Catbert3_vLogin
        [FISDataMartModel.Store.Catbert3_vLogin](T1.[Catbert3_vLogin.LoginID], T1.[Catbert3_vLogin.UserID])
    FROM (
        SELECT 
            T.LoginID AS [Catbert3_vLogin.LoginID], 
            T.UserID AS [Catbert3_vLogin.UserID], 
            True AS _from0
        FROM FISDataMartEntities.Catbert3_vLogin AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartEntities.Catbert3_vLogin
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartEntities.Catbert3_vLogin", @"
    SELECT VALUE -- Constructing Catbert3_vLogin
        [FISDataMartModel.Catbert3_vLogin](T1.[Catbert3_vLogin.LoginID], T1.[Catbert3_vLogin.UserID])
    FROM (
        SELECT 
            T.LoginID AS [Catbert3_vLogin.LoginID], 
            T.UserID AS [Catbert3_vLogin.UserID], 
            True AS _from0
        FROM FISDataMartModelStoreContainer.Catbert3_vLogin AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartModelStoreContainer.Catbert3_vSchools
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartModelStoreContainer.Catbert3_vSchools", @"
    SELECT VALUE -- Constructing Catbert3_vSchools
        [FISDataMartModel.Store.Catbert3_vSchools](T1.[Catbert3_vSchools.SchoolCode], T1.[Catbert3_vSchools.ShortDescription], T1.[Catbert3_vSchools.LongDescription], T1.[Catbert3_vSchools.Abbreviation])
    FROM (
        SELECT 
            T.SchoolCode AS [Catbert3_vSchools.SchoolCode], 
            T.ShortDescription AS [Catbert3_vSchools.ShortDescription], 
            T.LongDescription AS [Catbert3_vSchools.LongDescription], 
            T.Abbreviation AS [Catbert3_vSchools.Abbreviation], 
            True AS _from0
        FROM FISDataMartEntities.Catbert3_vSchools AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartEntities.Catbert3_vSchools
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartEntities.Catbert3_vSchools", @"
    SELECT VALUE -- Constructing Catbert3_vSchools
        [FISDataMartModel.Catbert3_vSchools](T1.[Catbert3_vSchools.SchoolCode], T1.[Catbert3_vSchools.ShortDescription], T1.[Catbert3_vSchools.LongDescription], T1.[Catbert3_vSchools.Abbreviation])
    FROM (
        SELECT 
            T.SchoolCode AS [Catbert3_vSchools.SchoolCode], 
            T.ShortDescription AS [Catbert3_vSchools.ShortDescription], 
            T.LongDescription AS [Catbert3_vSchools.LongDescription], 
            T.Abbreviation AS [Catbert3_vSchools.Abbreviation], 
            True AS _from0
        FROM FISDataMartModelStoreContainer.Catbert3_vSchools AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartModelStoreContainer.PPSDataMart_vSchools
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartModelStoreContainer.PPSDataMart_vSchools", @"
    SELECT VALUE -- Constructing PPSDataMart_vSchools
        [FISDataMartModel.Store.PPSDataMart_vSchools](T1.[PPSDataMart_vSchools.SchoolCode], T1.[PPSDataMart_vSchools.ShortDescription], T1.[PPSDataMart_vSchools.LongDescription], T1.[PPSDataMart_vSchools.Abbreviation])
    FROM (
        SELECT 
            T.SchoolCode AS [PPSDataMart_vSchools.SchoolCode], 
            T.ShortDescription AS [PPSDataMart_vSchools.ShortDescription], 
            T.LongDescription AS [PPSDataMart_vSchools.LongDescription], 
            T.Abbreviation AS [PPSDataMart_vSchools.Abbreviation], 
            True AS _from0
        FROM FISDataMartEntities.PPSDataMart_vSchools AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartEntities.PPSDataMart_vSchools
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartEntities.PPSDataMart_vSchools", @"
    SELECT VALUE -- Constructing PPSDataMart_vSchools
        [FISDataMartModel.PPSDataMart_vSchools](T1.[PPSDataMart_vSchools.SchoolCode], T1.[PPSDataMart_vSchools.ShortDescription], T1.[PPSDataMart_vSchools.LongDescription], T1.[PPSDataMart_vSchools.Abbreviation])
    FROM (
        SELECT 
            T.SchoolCode AS [PPSDataMart_vSchools.SchoolCode], 
            T.ShortDescription AS [PPSDataMart_vSchools.ShortDescription], 
            T.LongDescription AS [PPSDataMart_vSchools.LongDescription], 
            T.Abbreviation AS [PPSDataMart_vSchools.Abbreviation], 
            True AS _from0
        FROM FISDataMartModelStoreContainer.PPSDataMart_vSchools AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartModelStoreContainer.UnitFiles
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartModelStoreContainer.UnitFiles", @"
    SELECT VALUE -- Constructing UnitFiles
        [FISDataMartModel.Store.UnitFiles](T1.UnitFiles_Id, T1.UnitFiles_UnitId, T1.UnitFiles_Filename, T1.UnitFiles_SchoolCode, T1.UnitFiles_Created, T1.UnitFiles_CreatedBy, T1.UnitFiles_Uploaded, T1.UnitFiles_UploadedBy)
    FROM (
        SELECT 
            T.Id AS UnitFiles_Id, 
            T.UnitId AS UnitFiles_UnitId, 
            T.Filename AS UnitFiles_Filename, 
            T.SchoolCode AS UnitFiles_SchoolCode, 
            T.Created AS UnitFiles_Created, 
            T.CreatedBy AS UnitFiles_CreatedBy, 
            T.Uploaded AS UnitFiles_Uploaded, 
            T.UploadedBy AS UnitFiles_UploadedBy, 
            True AS _from0
        FROM FISDataMartEntities.UnitFiles AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FISDataMartEntities.UnitFiles
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FISDataMartEntities.UnitFiles", @"
    SELECT VALUE -- Constructing UnitFiles
        [FISDataMartModel.UnitFile](T1.UnitFile_UnitId, T1.UnitFile_Filename, T1.UnitFile_SchoolCode, T1.UnitFile_Id, T1.UnitFile_Created, T1.UnitFile_CreatedBy, T1.UnitFile_Uploaded, T1.UnitFile_UploadedBy)
    FROM (
        SELECT 
            T.UnitId AS UnitFile_UnitId, 
            T.Filename AS UnitFile_Filename, 
            T.SchoolCode AS UnitFile_SchoolCode, 
            T.Id AS UnitFile_Id, 
            T.Created AS UnitFile_Created, 
            T.CreatedBy AS UnitFile_CreatedBy, 
            T.Uploaded AS UnitFile_Uploaded, 
            T.UploadedBy AS UnitFile_UploadedBy, 
            True AS _from0
        FROM FISDataMartModelStoreContainer.UnitFiles AS T
    ) AS T1");
        }
    }
}
