//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public bool Inactive { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
