//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.ApplicationRoles = new HashSet<ApplicationRole>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int RoleID { get; set; }
        public string Role1 { get; set; }
        public bool Inactive { get; set; }
    
        public virtual ICollection<ApplicationRole> ApplicationRoles { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
