//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitFile
    {
        public int Id { get; set; }
        public int UnitId { get; set; }
        public string Filename { get; set; }
        public string SchoolCode { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Uploaded { get; set; }
        public string UploadedBy { get; set; }
    }
}
