//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Unit1 = new HashSet<Unit>();
            this.UnitAssociations = new HashSet<UnitAssociation>();
        }
    
        public int UnitID { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string PPS_Code { get; set; }
        public string FIS_Code { get; set; }
        public string SchoolCode { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Type { get; set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<Unit> Unit1 { get; set; }
        public virtual Unit Unit2 { get; set; }
        public virtual ICollection<UnitAssociation> UnitAssociations { get; set; }
    }
}
