//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BenefitsAllocationUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitFile
    {
        public int Id { get; set; }
        public int UnitId { get; set; }
        [Display(Name = "File Name")]
        public string Filename { get; set; }
        public string SchoolCode { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Uploaded { get; set; }
        public string UploadedBy { get; set; }

        /// <summary>
        /// Set this to determine if the file is available for download.
        /// </summary>
        public bool IsAvailable { get; set; }
    }
}
